# Site
repository: iamhyc/iamhyc.github.io
favicon: /assets/favicon.ico

#=========================== SEO Section ===========================
title: 洪云聪-HONG Yuncong-Yuncong Hong # title of the homepage
# description: #short description of your site
# author: #author's name
# google_analytics: # google analytics key
#=========================== SEO Section ===========================

# Personal info
name: HONG Yuncong
job_title: Ph.D Candidate
company: The University of Hong Kong
address: RSC M-13, G/F Haking Wong Building, HKU
email: ychong@cs.hku.hk
website: github.com/iamhyc

# Social links
#twitter_username: sudo_free
google_scholar_name: UgjDxNkAAAAJ
github_username:  iamhyc
linkedin_username: yuncong-hong-46a3aa172

# About Section
about_title: About Me
about_profile_image: images/BZ1808231652543091.jpg
about_content: | # this will include new lines to allow paragraphs
  Yuncong Hong (洪云聪) is currently a PhD candidate of Computer Science in a joint PhD programme offered by HKU and SUSTech.
  His supervisors are [Prof. Francis C.M. Lau](http://www.cs.hku.hk/~fcmlau) and [Prof. Rui Wang](https://eee.sustech.edu.cn/p/wangrui/).
  He received B.Eng from SUSTech in Communication Engineering.
  
  His research interests include scheduling problems in edge computing system, where the distributed or pipeline parallelism designs are considered.
  He is also interested in software programming and currently working on a fantastic program [VDM](https://github.com/VDM-Maintainer-Group/virtual-domain-manager).
  His programming skills are listed but not limited in the following areas: `Python`, `Rust`, `C/CPP`, `Nodejs`, `TypeScript`, and etc.
  
  [[My Curriculum Vitae]](assets/ychong_resume.pdf)  [[我的简历]](assets/ychong_resume_cn.pdf)

# Experience Section
experience_title: Research Experience #(Use this to override about experience section title)

# Publication Section
publication_title: Selected Publications #(Use this to override about more section title)
publication_content: | # Markdownify area
  [1] **Y. Hong**, B. Lv, R. Wang, H. Tan, Z. Han, H. Zhou, F. C. M. Lau, ``[Online Distributed Job Dispatching with Outdated and Partially-Observable Information](https://arxiv.org/abs/2012.13756),'' in Proc. IEEE MSN, 2020 **Best Track Paper Award**.
  
  [2] **Y. Hong**, B. Lv, R. Wang, H. Tan, Z. Han, F. C. M. Lau, ``[Distributed Job Dispatching in Edge Computing Networks with Random Transmission Latency: A Low-Complexity POMDP Approach](https://ieeexplore.ieee.org/document/9509750),'' in IEEE Internet of Things Journal, doi: 10.1109/JIOT.2021.3103798.
  
  [3] L. Zhou, **Y. Hong**, S. Wang, R. Han, D. Li, R. Wang, and Q. Hao, "[Learning centric wireless resource allocation for edge computing: Algorithm and experiment](https://ieeexplore.ieee.org/document/9307274)," IEEE Transactions on Vehicular Technology, Jan. 2021.

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme
remote_theme: sproogen/modern-resume-theme #(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
