# Site
repository: iamhyc/iamhyc.github.io
favicon: /assets/favicon.ico

#=========================== SEO Section ===========================
title: 洪云聪-HONG Yuncong-Yuncong Hong # title of the homepage
# description: #short description of your site
# author: #author's name
#=========================== SEO Section ===========================

# Personal info
name: HONG Yuncong
job_title: Ph.D Candidate
company: The University of Hong Kong
address: RSC M-13, G/F Haking Wong Building, HKU
email: ychong@cs.hku.hk
website: https://github.com/iamhyc

# Social links
twitter_username: sudo_free
# facebook_username: sudo_free
github_username:  iamhyc
linkedin_username: yuncong-hong-46a3aa172

# About Section
about_title: About Me
about_profile_image: images/BZ1808231652543091.jpg
about_content: | # this will include new lines to allow paragraphs
  HONG Yuncong (洪云聪) is currently a PhD student ot Computer Science at HKU, and my supervisor is [Prof. Francis C.M. Lau](http://www.cs.hku.hk/~fcmlau). I received my B.Eng from Southern University of Science and Technology (SUSTech) in Communication Engineering. And I am now in the joint PhD program between HKU and SUSTech.
  
  My research interest is now in scheduling problem in distributed system. And I am quite mania about coding softwares in the real system.
  My programming skills are listed but not limited in the following areas:
  `C/CPP` `Java` `Python` `Nodejs` `LabVIEW` `MATLAB` `Web`.

# Experience Section
experience_title: Research Experience #(Use this to override about experience section title)

# Publication Section
publication_title: Selected Publications #(Use this to override about more section title)
publication_content: | # Markdownify area

# Projects Section
projects_title: Projects #(Use this to override about projects section title)

# Education Section
educaton_title: Education #(Use this to override about education section title)

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme
remote_theme: sproogen/modern-resume-theme #(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
